# ----------------------------------------------------------------------------
#   Find Dependencies
# ----------------------------------------------------------------------------

if (NOT WIN32)
    return()
endif ()

message("--------------------------------------------")
message("-")
message("-")
message("-")
message("-")
message("start to find window dependencies....")

set(CUSTOM_LIB_DIR "C:/Program Files/CppLibrary")
set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} "${CUSTOM_LIB_DIR}/opencv/build")
set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} "${CUSTOM_LIB_DIR}/boost/lib/cmake")
set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} "${CUSTOM_LIB_DIR}/eigen/share/eigen3/cmake")
set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} "${CUSTOM_LIB_DIR}/poco/cmake")
set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} "${CUSTOM_LIB_DIR}/Ceres/lib/cmake/Ceres")
set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} "${CUSTOM_LIB_DIR}/aruco/share/aruco")
set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} "${CUSTOM_LIB_DIR}/vtk/lib/cmake")

message("find eigen...")
include(cmake/window/find_win_eigen.cmake)
#message("find opencv...")
#include(cmake/window/find_win_opencv.cmake)
#message("find ceres...")
#include(cmake/window/find_win_ceres.cmake)
#message("find aruco...")
#include(cmake/window/find_win_aruco.cmake)
message("find boost...")
include(cmake/window/find_win_boost.cmake)
message("find fmt...")
include(cmake/window/find_win_fmt.cmake)
#message("find poco...")
#include(cmake/window/find_win_poco.cmake)
message("find nlohmann...")
include(cmake/window/find_win_nlohmann.cmake)
#message("find spdlog...")
#include(cmake/window/find_win_spdlog.cmake)
message("find qt...")
include(cmake/window/find_win_qt.cmake)
#message("find vtk...")
#include(cmake/window/find_win_vtk.cmake)
#message("find pcl...")
#include(cmake/window/find_win_pcl.cmake)

message("find window dependencies finish")

message("-")
message("-")
message("-")
message("-")
message("--------------------------------------------")
